### ISSUE TITLE
xowa causes an exception on Mac OSX

### ISSUE THREAD

**Issue by ryho** [gnosygnu/xowa#18]
I'm on Mac OSX Yosemite V10.10.4
First I unzipped the zip file, and double clicked on the jar file, and it said it couldn't be opened.
Then I read the read me like I should have, and moved the files to the Users/user/xoma, and ran "sh /Users/your_user_name/xowa/xowa_macosx_64.sh"
Exception in thread "Thread-1" java.lang.UnsupportedClassVersionError: gplx/xowa/Xowa_main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by markusmaresch** [comment]
I am also on Mac OSX Yosemite V10.10.4
Looking for a simple clickable start-icon, I created a simple Xowa.app with Automator.
All it does, is execute /Users/.../xowa/xowa.sh as a shell script in /bin/bash
Maybe that helps.

Other checks:
Works: sh /Users/.../xowa/xowa.sh
Works: /Users/.../xowa/xowa.sh   (after doing one time: chmod +x /Users/.../xowa/xowa.sh

Check the Java-Environment with: env | grep JAVA
I have set this once in .bash_profile :
export JAVA_HOME=/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

Hope that helps
Markus

**Comment by gnosygnu** [comment]
Hi! Sorry for the delayed response, but release days are always difficult.

@markusmaresch Thanks for the suggestions! Also, I've had other Mac OS X users do the same thing with Automator and this should work fine.

@ryho Unfortunately, on Mac OS X, you can't just double-click the .jar file. markusmaresch's tip should work. To be explicit:

* if your files are at "Users/user/xoma", you should run <code>sh /Users/user/xoma/xowa_macosx_64.sh</code>
* if this fails, check your java environment with <code>env | grep JAVA</code> . Post the output here

Hope this helps.

**Comment by gnosygnu** [comment]
I'm marking this issue closed for now. If XOWA still doesn't work on Mac OS X, let me know and I'll reopen it.

Thanks.
