### ISSUE TITLE
searching concerns

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#265]
When using Special:XowaSearch I have come across a few issues

If the search string I use returns no results the 'search' never terminates
(The green pulsing sign to the right of the Search button)

If I use the search term `*bod`, the logs show an error

     failed to search_wiki; err=[err 0] <org.apache.lucene.queryparser.classic.ParseException> 
     Cannot parse '*bod': '*' or '?' not allowed as first character in WildcardQuery
     [err 1] <lucene_index> failed to exec seearch: query=*bod

 But nothing appears on screen

If I use the search term `bod*`, the logs show a different error

    Exception in thread "search" java.lang.NoClassDefFoundError: org/apache/lucene/search/join/ToParentBlockJoinQuery
        at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.extract(WeightedSpanTermExtractor.java:168)
        at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.getWeightedSpanTerms(WeightedSpanTermExtractor.java:518)

again nothing appears on screen

I think it would be reasonable to say `No results match query` or what ever (This would also need to be internationalised)
Return errors messages would be OK as well (although how these might be internationalised is a different matter)

In the last case I think it is the highlight logic that cant cope, so there should be some coding to do so

**Comment by gnosygnu** [comment]
Agreed on all three counts. I'll add this to my todo list and try to have something in the near-future. Thanks
