### ISSUE TITLE
Xowa App does not start on Android 9

### ISSUE THREAD

**Issue by AaronSchulz** [gnosygnu/xowa#558]
Everytime I start the app (even after clearing all data) I get:

Package: org.xowa
Version Code: 175
Version Name: 2.1.175-r-2018-01-05
Android: 9
Manufacturer: Samsung
Model: SGH-M919
CrashReporter Key: E09FCAA4-6DB8-D2C9-EC23-B6B5D4D08AE269C87688
Date: Sat Aug 24 14:15:19 PDT 2019

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.xowa/org.wikipedia.page.PageActivity}: gplx.Err: cfg.missing: grp=xowa.bldr.session key=wiki_domain
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: gplx.Err: cfg.missing: grp=xowa.bldr.session key=wiki_domain
	at gplx.Err_.new_wo_type(Err_.java:8)
	at gplx.dbs.cfgs.Db_cfg_tbl.Select_str(Db_cfg_tbl.java:91)
	at gplx.dbs.cfgs.Db_cfg_tbl.Select_bry(Db_cfg_tbl.java:80)
	at gplx.xowa.wikis.Xoa_wiki_mgr_.Import_by_url(Xoa_wiki_mgr_.java:8)
	at gplx.xowa.apps.Xoav_wiki_mgr.Import_by_url(Xoav_wiki_mgr.java:19)
	at gplx.xowa.drds.Xod_app_mgr.Load_wiki_by_url(Xod_app_mgr.java:221)
	at gplx.xowa.drds.Xod_app_mgr.Boot(Xod_app_mgr.java:166)
	at gplx.xowa.drds.Xod_app_mgr.Wikis_installed_count(Xod_app_mgr.java:194)
	at org.wikipedia.page.PageActivity.handleIntent(PageActivity.java:452)
	at org.wikipedia.page.PageActivity.onCreate(PageActivity.java:280)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	... 11 more
Description: {}

**Comment by gnosygnu** [comment]
Hi! Thanks for filing the issue, as well as the stack trace

Unfortunately, I wasn't able to reproduce the error. More details below. I'm not sure why though it's possible it can be device related.

Just to ask, is this a standard installation? Specifically:
* Stock Samsung Galaxy S4 device
* XOWA app installed from Google Play (last updated 2018-01)
* Gave permission to XOWA for accessing Photos / Videos (Filesystem permissions)

If so, then I'll try:
* To get a Samsung Galaxy S4 and reproduce
* Faling that, build another apk with more logging around the boot location and see if you can give it a try

Hope that works for you. Thanks!

---

It looks like your device is a Samsung Galaxy S4 (based on SGH-M919). For what it's worth, my device is a Samsung S8+ on Android 9 (Pie)

I uninstalled the XOWA app on my phone, and then downloaded the version from Google Play. I was able to open it on my side.

The call stack is a bit weird as it's failing to load configuration settings which comes from a database distributed with the apk.

**Comment by AaronSchulz** [comment]
It has LineageOS 16 (20190820-NIGHTLY-jfltexx). It worked before when I was on 14.1.

It's the regular APK from the play store (Jan 2018) and has the SD card permission (Samsung Evo 256GB, much faster than my old 200GB PNY).

**Comment by gnosygnu** [comment]
> It has LineageOS 16 (20190820-NIGHTLY-jfltexx). It worked before when I was on 14.1.

Cool. Thanks for the follow-up . At this point, let me look at getting a budget Android device and installing LineageOS + Android 9 on it. This will probably take a week or two, so sorry for the delay

**Comment by AaronSchulz** [comment]
My new Galaxy A20 with stock android 9 (plus stock Samsung stuff) does not seem to have this problem. The file browser also seems to actually work on that phone as well...import from my PC was just copy/paste/open.

**Comment by el-komodos-drago** [comment]
Having a nearly identical issue on a stock Android 9 Nokia 2.3.
(side note: I am setting up instructions for users of my Wiki to access it offline. Is there any fundraiser/kickstarter you would like me to point iPhone users to?)

**Comment by gnosygnu** [comment]
Sorry for the delay. I've moved this issue back to TODO, especially as I'm planning to refresh the Android version for #708

**Comment by gnosygnu** [comment]
Just a status report. I looked at this over the weekend, and am having build issues with the code base, primarily due to changes in Android Studio. I'm going to explore re-building with the latest Wikipedia Android app code-base, or trying to force something with the current XOWA version.

I'll work on this throughout the week, and report back next weekend.

**Comment by gnosygnu** [comment]
Another status report. I looked at the latest Wikimedia Android version, and there will be a lot of rewriting (the core PageLoadStrategy went away)

I'll take a look at doing an intermediary release with the old XOWA app version for debugging purposes. But the next official XOWA Android release may become a large-scale issue to upgrade to the latest Wikimedia App, which has been partially forced due to (a) Android Studio (b) Java 8 and (c) Google Play policies

**Comment by gollum-z** [comment]
Hello,
I have the same problem on my Fairphone 2. 
I recently updated to Android 9 (i.e. FairphoneOpen 21.03.0-rel2) and now the app shows almost the same error on start and won’t launch. On the previous system version (7.1.2) it worked fine.
