### ISSUE TITLE
Embeddable: NPE on  Hxtn_page_mgr.Page_tbl__insert

### ISSUE THREAD

**Issue by oakenshield** [gnosygnu/xowa#733]
Certain pages produce an NPE when using der Xop_mediawiki_wkr API

See: https://www.dropbox.com/s/ct4akls7qojfuj2/XOWATest.zip?dl=0 for a self-contained example

Exception in thread "main" java.lang.NullPointerException
    at gplx.xowa.htmls.hxtns.pages.Hxtn_page_mgr.Page_tbl__insert(Unknown Source)
    at gplx.xowa.xtns.template_styles.Template_styles_nde.Xtn_write(Unknown Source)
    at gplx.xowa.htmls.core.htmls.Xoh_html_wtr.Xnde(Unknown Source)
    at gplx.xowa.htmls.core.htmls.Xoh_html_wtr.Write_tkn(Unknown Source)
    at gplx.xowa.htmls.core.htmls.Xoh_html_wtr.Write_tkn(Unknown Source)
    at gplx.xowa.htmls.core.htmls.Xoh_html_wtr.Write_doc(Unknown Source)
    at gplx.xowa.htmls.Xoh_page_wtr_wkr.Write_body_wikitext(Unknown Source)
    at gplx.xowa.htmls.Xoh_page_wtr_wkr.Write_body(Unknown Source)
    at gplx.xowa.htmls.Xoh_page_wtr_wkr.Write_hdump(Unknown Source)
    at gplx.xowa.addons.parsers.mediawikis.Xop_mediawiki_wkr.Parse(Unknown Source)
    at org.xowatest.XOWAParser.parse(XOWAParser.java:36)
    at org.xowatest.XOWATest.main(XOWATest.java:10)

**Comment by gnosygnu** [comment]
Hey, thanks for creating the issue. Trying to finish up #721. Will take a look at this issue and the others afterwards.

**Comment by oakenshield** [comment]
Thank you @gnosygnu . Glad that you are still active on the project. The issue hasn't been around in v4.5.21.1808, but I haven't tested yet, when it first appeared. I considered using this version but given all the updates since then I think it's worth waiting for the fix. Is a rough estimate possible? The other issues I mentioned in the mail stem from not providing module-pages - I could easily fix that on my part.

**Comment by gnosygnu** [comment]
Thanks for the sample project!

I see the problem. Let me see if there's a "clean" fix for it. If not, I'll just do a null check. I should be able to have an unofficial beta version by tomorrow morning.

More details below.

---

First, some background. The `Xop_mediawiki_wkr` allows generating HTML by:
* Getting Wikitext from calling a MediaWiki instance
* Parsing that Wikitext through the XOWA parser

Unfortunately, the `Xop_mediawiki_wkr` is using the same code pathway as the HTML dump code. Some time ago, I've changed this HTML dump code to also generate HTML databases for Extension HTML metaData (in this case, the CSS styles for TemplateStyles). As it turns out, this change (HXTN) is only initialized in `Xomp_parse_wkr`, not in `Xop_mediawiki_wkr`. No initialization causes the NPE above.

The simplest fix would be a null pointer check, but the HXTN code sits in different parts of the code, so that could mean multiple checks (and I could miss one). I just want to see if there's a cleaner solution.

**Comment by gnosygnu** [comment]
Fixed with the commit above. Also built a new version here: https://github.com/gnosygnu/xowa/releases/tag/v4.6.7.2005 . Let me know if you run into any issues

Thanks!
