### ISSUE TITLE
NPE in Embedded Mode

### ISSUE THREAD

**Issue by oakenshield** [gnosygnu/xowa#753]
On some pages the following exception is thrown:

Exception in thread "main" java.lang.NullPointerException
	at gplx.xowa.htmls.core.htmls.Xoh_html_wtr.Xnde(Unknown Source)
	at gplx.xowa.htmls.core.htmls.Xoh_html_wtr.Write_tkn(Unknown Source)
	at gplx.xowa.htmls.core.htmls.Xoh_html_wtr.Write_xnde(Unknown Source)
	at gplx.xowa.htmls.core.htmls.Xoh_html_wtr.Xnde(Unknown Source)
	at gplx.xowa.htmls.core.htmls.Xoh_html_wtr.Write_tkn(Unknown Source)
	at gplx.xowa.htmls.core.htmls.Xoh_html_wtr.Write_tkn(Unknown Source)
	at gplx.xowa.htmls.core.htmls.Xoh_html_wtr.Write_doc(Unknown Source)
	at gplx.xowa.htmls.Xoh_page_wtr_wkr.Write_body_wikitext(Unknown Source)
	at gplx.xowa.htmls.Xoh_page_wtr_wkr.Write_body(Unknown Source)
	at gplx.xowa.htmls.Xoh_page_wtr_wkr.Write_hdump(Unknown Source)
	at gplx.xowa.addons.parsers.mediawikis.Xop_mediawiki_wkr.Parse(Unknown Source)

The following project demonstrates the Exception:
https://www.dropbox.com/s/hz4xdoy27zn6ncj/XOWATest.zip?dl=0

**Comment by gnosygnu** [comment]
Thanks for creating the issue as well as the test project.

This NPE is related to a recent issue: #730. I was able to reproduce the failure with XOWATest, and was able to fix by just changing the dependencies to the latest source.

I built a new unofficial release from latest here: https://github.com/gnosygnu/xowa/releases/tag/v4.6.8.2006

I'm hoping to have an official release when I finish 2020-06 dewiki (in the next two or three days)

Let me know if anything else. Thanks!
